// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxx_DrKvwhuiBj3-Q8u6Kmd_WB00-1Mlg',
    appId: '1:816669266031:web:0840b24f3110cf54d97d9a',
    messagingSenderId: '816669266031',
    projectId: 'expirywise-app-bf1fc',
    authDomain: 'expirywise-app-bf1fc.firebaseapp.com',
    storageBucket: 'expirywise-app-bf1fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiko_MtPSfPMQK_Sf60i0PauzVJ59GW8o',
    appId: '1:816669266031:android:3b265d7a2f13f88fd97d9a',
    messagingSenderId: '816669266031',
    projectId: 'expirywise-app-bf1fc',
    storageBucket: 'expirywise-app-bf1fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVsUxGPdEJ-T2N2ibdkq5x2p8LhTSDpmw',
    appId: '1:816669266031:ios:473948f1551f102cd97d9a',
    messagingSenderId: '816669266031',
    projectId: 'expirywise-app-bf1fc',
    storageBucket: 'expirywise-app-bf1fc.firebasestorage.app',
    iosClientId: '816669266031-i1gfpeh50agj33i10ct0vatlgbgre6ld.apps.googleusercontent.com',
    iosBundleId: 'com.example.expiryWiseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVsUxGPdEJ-T2N2ibdkq5x2p8LhTSDpmw',
    appId: '1:816669266031:ios:473948f1551f102cd97d9a',
    messagingSenderId: '816669266031',
    projectId: 'expirywise-app-bf1fc',
    storageBucket: 'expirywise-app-bf1fc.firebasestorage.app',
    iosClientId: '816669266031-i1gfpeh50agj33i10ct0vatlgbgre6ld.apps.googleusercontent.com',
    iosBundleId: 'com.example.expiryWiseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxx_DrKvwhuiBj3-Q8u6Kmd_WB00-1Mlg',
    appId: '1:816669266031:web:3ee0764a8984c0b9d97d9a',
    messagingSenderId: '816669266031',
    projectId: 'expirywise-app-bf1fc',
    authDomain: 'expirywise-app-bf1fc.firebaseapp.com',
    storageBucket: 'expirywise-app-bf1fc.firebasestorage.app',
  );
}
